### ISSUE TITLE
The recommended no. of concurrent workers

### ISSUE THREAD

**Issue by ealashwali** [prbinu/tls-scan#10]
Hi, I would like to run tls-scan with --concurrency option set to perform the scan as fast as possible. The readme says:

> Concurrency should be set based on your system capacity (memory, cpu, network) etc. Default: 1.

If I'm using Ubuntu 18 with 16 GB RAM and Intel Core i7 2.6 GHz processor, can you suggest the suitable value? Can you provide your experience values as guidance for selecting the most suitable value of this parameter?

**Comment by ealashwali** [comment]
Thanks. But how settings concurrency argument benefits the performance if I'm using tls-scan to perform handshakes with domain names (no ciphersuites enumeration here). Since tls-scan is single thread, isn't going to make one TLS connection at a time and wait till it finishes, then do the second?

**Comment by prbinu** [comment]
No, that is not true. tls-scan is single threaded, but the connections are non-blocking. Hence it can handle large number of concurrent connections.

**Comment by ealashwali** [comment]
For your previous post, 

> Speed: 1000Mb/s <== This may not be adequate, depending up on your CPU capacity)

Not adequate even for 10 concurrent workers?

**Comment by ealashwali** [comment]
I will appreciate your advise in this issue. My network hardware capacity is: 867 Mbps. I have 4 i7 cores and 16 GB RAM. I run `nload` to monitor the network. I am sorry but could not find a good reference to help me interpret the output. I see the maximum 2.03 Mbit and this value increases when I increase the concurrent workers. Can you please advise me on this? Do you think I can increase till I reach 100s of Mbps? Can you see the screenshot here? https://github.com/ealashwali/public-photos/blob/master/5000_concurrent_edited.png

**Comment by prbinu** [comment]
Based on the second screenshot, it seems like you are only consuming < 600KB/sec is approx 5Mb/sec. So NIC is not saturated with 5000 concurrent connections. Since it is a single process, your one CPU would have hit the max. Also make sure you use ethernet cable, not wireless router.

**Comment by ealashwali** [comment]
Thanks. I use wireless at the moment (testing) as I do not have wired card in my device. If I will use wired, it will be USB-to-Eth. I hope Linux nethogs can detect tit? 
I have two questions please: 1) when my device hardware capacity is not coping with the no. of concurrent workers, do I lose connections (dropped) or the requests wait? and it is just that I do not get the expected performance? 
2) The link photo is for 10 concurrent workers. Does this seem the optimal no. for my current settings? https://github.com/ealashwali/public-photos/blob/master/nethogs-10-concurrent.png

**Comment by prbinu** [comment]
Like I said before, there are many reasons that can impact your performance. Unless you are doing research on performance, I would suggest to try few combination and stick with a reasonable setting. Worst case, it takes couple more hours to complete the scan (if the scan is in the order of 100k servers). 

Connections are not dropped, but if it takes more time, then it may get timeout errors.
