### ISSUE TITLE
strings from certificate are broken

### ISSUE THREAD

**Issue by EnDe** [prbinu/tls-scan#2]
if the text in the certificate (i.e. issuer or subject) contains " (double-quote), they are removed from the output

**Comment by prbinu** [comment]
Good catch! 
Its a hack to avoid breaking JSON output. Yeah I could have escaped it, but that would be an expensive operation and require new buffer. I was thinking that that given a certificate fingerprint, we can easily find the certificate details. I would like to know your thoughts on this.

thank you!

**Comment by EnDe** [comment]
hmm, a computer is there to do what I want, not the other way around.
IMHO changing the string is a bug.
But wait, we're having "alternative facts" nowerdays :-/

**Comment by prbinu** [comment]
Yes, this is less than ideal state, but low priority for now. I will try to address this when i get some time between my regular schedule.

**Comment by prbinu** [comment]
This is now fixed in the latest ([1.4.6](https://github.com/prbinu/tls-scan/releases/tag/1.4.6)) release
