### ISSUE TITLE
Feature request: Support for TLS 1.3?

### ISSUE THREAD

**Issue by ealashwali** [prbinu/tls-scan#20]
If I compile the code using TLS 1.3 supporting library, does tls-scan recognises TLS 1.3?

**Comment by ealashwali** [comment]
I will appreciate letting me know whether this feature can be added in the mean time, or not.

**Comment by prbinu** [comment]
i can give it a shot. give me a week.

**Comment by prbinu** [comment]
Try this: https://github.com/prbinu/tls-scan/blob/master/build-x86-64-openssl-1.1.1.sh

The above script builds tls-scan with TLS-1.3 support
Tested on Ubuntu-16.04
