### ISSUE TITLE
Feature request: add the handshake perf. time (time to complete a handshake)

### ISSUE THREAD

**Issue by ealashwali** [prbinu/tls-scan#23]
If you can add this feature that shows how much time in milliseconds does each handshake took to complete (i.e. performance time) with each handshake in the json file, it is going to be very useful. A sister tool called sslscan https://github.com/rbsec/sslscan does this but tl-scan is much efficient which I would like to use.

**Comment by prbinu** [comment]
give me few days. i will give it a try.

**Comment by prbinu** [comment]
Here is the code:
https://github.com/prbinu/tls-scan/commit/13fa688c1ddea474e421d45867eebfb6f22abcde

Added new field: `elapsedTime`. This is total time taken per host scan in milliseconds. 

Note: If you are doing only cert scan, it shows single session handshake time (i presume that is what you want). However if you use cipher/tlsversion enum scan, this field reflects aggregate time of all TLS handshakes performed against target host.
