### ISSUE TITLE
Feature Requets: Error Logging

### ISSUE THREAD

**Issue by ealashwali** [prbinu/tls-scan#24]
Hi, is it possible to add a feature for logging errors when the TLS handshake fails and can not obtain results? Mainly that specifies the domain name or IP address of the requested address, the error message, date/time and save them in a file? Can this be an argument in the command (so we enable it when needed).

**Comment by prbinu** [comment]
I thought it is already spitting error logs into stderr. Is that not sufficient?

If not, a sample output will help (what you are observing and what you expect).

**Comment by ealashwali** [comment]
Thanks. It is true the errors are shown in the console. But 

1) they are not saved in a file and there is no choice (argument) that allows me to do this. Using `tee` can cause slowness, or that what happened when I tries it with long run (50 concurrent connections and read a longs list of addresses from a file).

2) they do not provide timestamp with the error (do you think this is a good idea? if it affects performance, may be not)
  
This is one example that shows how the errors are displayed:

**Command:**
```
./tls-scan --connect=qq.com --port=443 --cacert=../../../../../etc/ssl/certs/ca-certificates.crt
```
**Output:**
host: qq.com; ip: ; error: Timeout

**Comment by prbinu** [comment]
1. Could this be solved by redirecting ('>') stderr to a file?
2. It is not hard to do, in timeout case, you already know the elapsed time.

**Comment by ealashwali** [comment]
Yes. Using `>` will save logs to a file, but I am looking for a way to still be able to see the progress in the terminal while having it saved in a file. However, I will close the issue.
