### ISSUE TITLE
--infile Domains w/ Port Numbers

### ISSUE THREAD

**Issue by rrioux** [prbinu/tls-scan#27]
When passing a list of domains with port numbers via --infile, name resolution errors are thrown. It appears to only support the domain, whereas I have them in the file as I would include them individually on the CLI.

For example:

domain.com:443
domain2.com:4443
domain3.com:8080

This is probably more of a feature request than an issue. Can this functionality be added?

Great product, BTW. Really helping with tracking all these certs and capabilities.

Thank you!

**Comment by prbinu** [comment]
Thanks Randal

 In most cases, this tool is used to scan multiple IPs, but one port (e.g 443). I'm aware of this issue, but when I looked closely today, it seems more like a bug.

I have the code changes, if you can't wait, you can easily clone and build yourself; or wait for the binary release

**Comment by prbinu** [comment]
fixed in https://github.com/prbinu/tls-scan/releases/tag/0.2.1
