### ISSUE TITLE
seems not to enumerate RC4 ciphers

### ISSUE THREAD

**Issue by EnDe** [prbinu/tls-scan#3]
...i.e. misses to detect ECDHE-RSA-RC4-SHA and RC4-SHA (did not test others like RC4-MD5)

**Comment by prbinu** [comment]
thanks for reporting this. seems like a bug in the code, with tls1_2.

For e.g., the following command actually enumerate RC4 ciphers:
tls-scan --host=rc4.badssl.com --cacert=../tls-scan/ca-bundle.crt --pretty -e --ssl3 --tls1 --tls1_1

Again, this is an issue that i will address soon.

**Comment by prbinu** [comment]
Fixed in 0.1.7 
release https://github.com/prbinu/tls-scan/releases/tag/0.1.7
