### ISSUE TITLE
GnuTLS Handshake Errors

### ISSUE THREAD

**Issue by rrioux** [prbinu/tls-scan#33]
Thanks for continuing the work on this tool. I just wanted to report an error I get when running scans, but it doesn't seem to effect the results.

host: hostname; ip: n.n.n.n; error: Network; errormsg:                Error encountered during GnuTLS handshake: -12                Unsupported TLS 1.3 version/cipher

Any idea what this is? If you need more data, please advise how you would like it generated.

Thanks!
Randal

**Comment by prbinu** [comment]
Hi Randal,

Based on the description you shared, it seems like the server you are trying to scan support neither TLS 1.3 nor a particular cipher you are trying.

You help further, please provide more details (and why do you think this is a bug, by comparing with other scan tools)

**Comment by rrioux** [comment]
It happens on thousands of domains. tls-scan versions prior to the TLS 1.3 support do not throw this error (hmm, I suppose that would be obvious!). 

I will narrow down a test set for FQDNs and see if I can't get more useful data.

Thanks!

**Comment by prbinu** [comment]
It think this is expected because only a few servers out there on Internet supports TLS 1.3. You can easily mute this noise by redirecting stderr to /dev/null (or to a file).
