### ISSUE TITLE
tls-scan not working 

### ISSUE THREAD

**Issue by omaramin17** [prbinu/tls-scan#36]
Hi @prbinu :)
While installing tls-scan on droplet form digital ocean . it gives me that ./tls-scan command not found . i make sure that i have installed requirements 
===========================================
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
gcc -DPACKAGE_NAME=\"tls-scan\" -DPACKAGE_TARNAME=\"tls-scan\" -DPACKAGE_VERSION=\"1.4.1\" -DPACKAGE_STRING=\"tls-scan\ 1.4.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tls-scan\" -DVERSION=\"1.4.1\" -I.  -I./include -I build-root/include -I build-root/include -Wall -Wundef -Wshadow -Wunreachable-code -Wswitch-default -Wcast-align -pedantic -g -std=c99 -D_GNU_SOURCE -DTS_VERSION=\"1.4.3\" -DTS_BUILD_DATE=\"2020-06-28\" -DTS_OS=\"Linux\"   -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
In file included from ./include/proto-adapters.h:8,
                 from main.c:29:
./include/common.h:18:10: fatal error: gnutls/gnutls.h: No such file or directory
 #include <gnutls/gnutls.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:439: main.o] Error 1
gcc -DPACKAGE_NAME=\"tls-scan\" -DPACKAGE_TARNAME=\"tls-scan\" -DPACKAGE_VERSION=\"1.4.1\" -DPACKAGE_STRING=\"tls-scan\ 1.4.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tls-scan\" -DVERSION=\"1.4.1\" -I.  -I./include -I build-root/include -I build-root/include -Wall -Wundef -Wshadow -Wunreachable-code -Wswitch-default -Wcast-align -pedantic -g -std=c99 -D_GNU_SOURCE -DTS_VERSION=\"1.4.3\" -DTS_BUILD_DATE=\"2020-06-28\" -DTS_OS=\"Linux\"   -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
In file included from ./include/proto-adapters.h:8,
                 from main.c:29:
./include/common.h:18:10: fatal error: gnutls/gnutls.h: No such file or directory
 #include <gnutls/gnutls.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:439: main.o] Error 1
>>> Complete
root@omar:~/aws/tls-scan# cd build-root/
root@omar:~/aws/tls-scan/build-root# cd bin/
root@omar:~/aws/tls-scan/build-root/bin# ./tls-scan
-bash: ./tls-scan: No such file or directory
root@omar:~/aws/tls-scan/build-root/bin# ./tls-scan --connect=yahoo.com --cacert=../etc/tls-scan/ca-bundle.crt --pretty
-bash: ./tls-scan: No such file or directory
root@omar:~/aws/tls-scan/build-root/bin# tls-scan
-bash: tls-scan: command not found
======================================
Thanks ,

**Comment by prbinu** [comment]
Hello, It is not clear in the report what steps you followed.

Build from source instructions: https://github.com/prbinu/tls-scan#build-from-source
Or use may binaries available for Linux and Mac: https://github.com/prbinu/tls-scan/releases/tag/1.4.3

**Comment by prbinu** [comment]
Hope this issue is resolved.

**Comment by omaramin17** [comment]
Hi @prbinu Unfortunately . i let it and i came back today trying to install it and that what i have done :)
git clone https://github.com/prbinu/tls-scan.git 
cd tls-scan 
./build-x86-64.sh
but it seems that there is some errors
=========================== 
 ./autogen.sh: 18: ./autogen.sh: aclocal: not found
./build-x86-64.sh: line 7: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
>>> Complete
============================
i tried installing it on 3 machines but same errors :(
Thanks,
