### ISSUE TITLE
Malformed JSON output leads to jq parsing error: "Expected another key-value pair at line X"

### ISSUE THREAD

**Issue by daehee** [prbinu/tls-scan#38]
tls-scan outputs a malformed JSON line item, which throws errors when trying to parse the output file with jq. 

jq error:
```
parse error: Expected another key-value pair at line 14607, column 43
```

Line 14607 in tls-scan output file -- notice ending with `,` char and missing `certificateChain` key.
```
{ "host": "XXX", "ip": "XXX", "port": 443, "elapsedTime": 611, "tlsVersion": "TLSv1.2", "cipher": "ADH-AES256-SHA          SSLv3 Kx=DH       Au=None Enc=AES(256)  Mac=SHA1", "tempPublicKeyAlg": "DH", "tempPublicKeySize": 2048, "secureRenego": true, "compression": "NONE", "expansion": "NONE", "sessionLifetimeHint": 300, "x509ChainDepth": -1, "verifyCertResult": true, "verifyHostResult": false, "ocspStapled": false, }
```

**Comment by prbinu** [comment]
@daehee  Can you share the (redacted) tls-scan output?

**Comment by prbinu** [comment]
@daehee I've made some code changes that is expected to fix this issue. 

Please test new binary and confirm.
https://github.com/prbinu/tls-scan/releases/tag/1.4.4

**Comment by daehee** [comment]
@prbinu just tested v1.4.4 and tripping on the same error. See output below:

![CleanShot 2020-09-08 at 19 44 45@2x](https://user-images.githubusercontent.com/81271/92548546-24d9bc00-f20c-11ea-8c66-5063adf4fd24.png)

The tls-scan output file is 456M, but I can email you snippets if it would be helpful.

Another jq parse error are invalid escape patterns `\*` in the certificate values.

![CleanShot 2020-09-08 at 19 52 56@2x](https://user-images.githubusercontent.com/81271/92548940-1344e400-f20d-11ea-9643-db505a2e5539.png)

**Comment by prbinu** [comment]
@daehee Please share the output snippets to prbinu@yahoo.com

**Comment by prbinu** [comment]
@daehee I've fixed the issue. Please try the new binary: https://github.com/prbinu/tls-scan/releases/tag/1.4.5

**Comment by daehee** [comment]
@prbinu I just ran another mass scan with tls-scan v1.4.5, and confirming that this latest release did clear those issues reported above. 

Another edge case discovered for: `Invalid string: control characters from U+0000 through U+001F`

![CleanShot 2020-09-11 at 19 12 28@2x](https://user-images.githubusercontent.com/81271/92984955-3537a400-f463-11ea-9a22-944dc59bc109.png)

**Comment by prbinu** [comment]
This should fix the issue. I have escaped all control chars.
https://github.com/prbinu/tls-scan/releases/tag/1.4.6

**Comment by daehee** [comment]
@prbinu closing the loop on this issue, this latest 1.4.6 release cleared all errors with jq parse of my sample output file.

**Comment by prbinu** [comment]
@daehee  thanks for confirming!
