### ISSUE TITLE
 seems not to enumerate CHACHA ciphers 

### ISSUE THREAD

**Issue by EnDe** [prbinu/tls-scan#4]
i.e. mail.google.com offers ECDHE-RSA-CHACHA20-POLY1305-SHA256

**Comment by prbinu** [comment]
The openssl fork we use doesn't support this cipher (yet).
Here is the tracking issue:
https://github.com/PeterMosmans/openssl/issues/38

**Comment by prbinu** [comment]
fixed in this release: https://github.com/prbinu/tls-scan/releases/tag/1.4.3
