### ISSUE TITLE
zlib-1.2.13 not available

### ISSUE THREAD

**Issue by jrhunger** [prbinu/tls-scan#59]
Following docker build instructions and the build failed due to http://zlib.net/zlib-1.2.13.tar.gz returning 404.
Making the below zlib version change to 1.3 allowed the build to complete, and seems functional.
```
diff --git a/bootstrap.sh b/bootstrap.sh
index 1cb8210..5029be6 100755
--- a/bootstrap.sh
+++ b/bootstrap.sh
@@ -45,7 +45,7 @@ export PKG_CONFIG_PATH=${OUTDIR}/lib/pkgconfig

 OPENSSL_VERSION="1.0.2-chacha"
 LIBEVENT_VERSION="2.1.8-stable"
-ZLIB_VERSION="zlib-1.2.13"
+ZLIB_VERSION="zlib-1.3"

```

**Comment by prbinu** [comment]
Thank you for sharing the patch; fixed in 1.5.2 release.
