### ISSUE TITLE
Install fails when trying to extract zlib-1.3.tar.gz

### ISSUE THREAD

**Issue by emailwedgy** [prbinu/tls-scan#60]
zlib has been updated to v1.3.1. Similar to issue #59. 

Running:
sudo ./bootstrap.h -v

Error:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

zlib-1.3.tar.gz contains a 404 not found message in html format, it is not a tar.gz.

Replace line 48:
ZLIB_VERSION="zlib-1.3"
with
ZLIB_VERSION="zlib-1.3.1"

Appears to install correctly after this change.

**Comment by prbinu** [comment]
@emailwedgy  thank you for reporting this issue. I've updated the zlib path.
