### ISSUE TITLE
Incorrect scan result with CHACHA cipher

### ISSUE THREAD

**Issue by ealashwali** [prbinu/tls-scan#8]
Hi, I am sure (by manual testing from a browser that only supports: ecdhe_rsa_chacha20_poly1305_sha256) that "google.com" supports ecdhe_rsa_chacha20_poly1305_sha256. 

However, when I perform a scan using: tls-scan, I do not get this cipher as a supported cipher by google.com. Can you please clarify the issue to me? CHACHA appears to be in the list of ciphers that tls-scan examined (according to the output) but this seems not the case.

**Comment by prbinu** [comment]
Thanks for the report. Seems like you are experiencing the same issue as this: https://github.com/prbinu/tls-scan/issues/4

I will put some cycles this week/next week and see whether i can add *chacha* support. Meanwhile if you already figured it out, please raise a PR

**Comment by ealashwali** [comment]
Hi. Just need to know if tls-scan can negotiate chacha ciphers?
